### ISSUE TITLE
A "Shop Now" button

### ISSUE THREAD

**Issue by sarahsga** [shefy123/exibition-task#3]
Add a `Shop Now` button in the home page, below "A Project by Zein" so the user has an obvious way to go to the products page. The Products are the most important part of the website, and it should be highlighted where to click.

**Comment by shefy123** [comment]
added

**Comment by sarahsga** [comment]
Can you center align it (along with the button heading)? Looks a little out of place. Also, can you increase the size of the `Show Now` button?

**Comment by shefy123** [comment]
Yes i will and button start with a project by zian ahmed heading its not
the center of the page ma'am but if you want it center i will do 😊
