### ISSUE TITLE
Style Adjustments

### ISSUE THREAD

**Issue by sarahsga** [shefy123/exibition-task#4]
While the webpage looks EXCELLENT, a few things can make it look even better:

1. Consider using [Bootstrap Cards](https://getbootstrap.com/docs/4.1/components/card/) for the products to give it a professional look. Also, Add proper margins between the cards.

![screen shot 2018-05-21 at 8 12 22 am](https://user-images.githubusercontent.com/10798986/40288850-b73a4ef0-5cce-11e8-9af3-61d1a6fce688.png)

Make sure you are using Flexbox here.

2. Consider using some FontAwesome icons in the footer to bring it to life:

![screen shot 2018-05-21 at 8 15 30 am](https://user-images.githubusercontent.com/10798986/40288952-32721d64-5ccf-11e8-8196-97e8d351898d.png)

3. The navbar and footer should be on every page. Please make your About page has the navbar.

**Comment by shefy123** [comment]
i have done

**Comment by sarahsga** [comment]
@shefy123 I reviewed. Looks perfect!!! Nice work!
