### ISSUE TITLE
Adjustments in Responsiveness

### ISSUE THREAD

**Issue by sarahsga** [shefy123/exibition-task#5]
Firstly, your homepage is perfectly responsive. No issues there. Good job!

However, the Fabric and the About page need a few tiny adjustments to make it look good on mobile devices:

- The about page should be responsive. Meaning that the user should not have to scroll horizontally to read the content. Here's how it looks like on my phone:

![screen shot 2018-05-21 at 8 19 47 am](https://user-images.githubusercontent.com/10798986/40289085-d3c1527a-5ccf-11e8-870c-50ff54dc28cf.png)

- The products page should be responsive (Are you using Flexbox? If not, please do). Here's how it looks like on my phone. Notice how the product cards overlap each other and look out of place:

![screen shot 2018-05-21 at 8 21 01 am](https://user-images.githubusercontent.com/10798986/40289123-09381ee8-5cd0-11e8-808e-6763d946feaf.png)

**Comment by shefy123** [comment]
i have change about page and solve second isssue

**Comment by sarahsga** [comment]
@shefy123 I checked. Was soo happy with your changes. I couldn't find any more issues in responsiveness. Super happy! :)

**Comment by shefy123** [comment]
Thanks alot ma'am 😊
